/**
 * generated by Xtext 2.19.0
 */
package org.openhab.core.model.thing.thing;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model Channel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.openhab.core.model.thing.thing.ModelChannel#getChannelKind <em>Channel Kind</em>}</li>
 *   <li>{@link org.openhab.core.model.thing.thing.ModelChannel#getType <em>Type</em>}</li>
 *   <li>{@link org.openhab.core.model.thing.thing.ModelChannel#getChannelType <em>Channel Type</em>}</li>
 * </ul>
 *
 * @see org.openhab.core.model.thing.thing.ThingPackage#getModelChannel()
 * @model
 * @generated
 */
public interface ModelChannel extends ModelPropertyContainer
{
  /**
   * Returns the value of the '<em><b>Channel Kind</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Channel Kind</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Channel Kind</em>' attribute.
   * @see #setChannelKind(String)
   * @see org.openhab.core.model.thing.thing.ThingPackage#getModelChannel_ChannelKind()
   * @model
   * @generated
   */
  String getChannelKind();

  /**
   * Sets the value of the '{@link org.openhab.core.model.thing.thing.ModelChannel#getChannelKind <em>Channel Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Channel Kind</em>' attribute.
   * @see #getChannelKind()
   * @generated
   */
  void setChannelKind(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.openhab.core.model.thing.thing.ThingPackage#getModelChannel_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.openhab.core.model.thing.thing.ModelChannel#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Channel Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Channel Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Channel Type</em>' attribute.
   * @see #setChannelType(String)
   * @see org.openhab.core.model.thing.thing.ThingPackage#getModelChannel_ChannelType()
   * @model
   * @generated
   */
  String getChannelType();

  /**
   * Sets the value of the '{@link org.openhab.core.model.thing.thing.ModelChannel#getChannelType <em>Channel Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Channel Type</em>' attribute.
   * @see #getChannelType()
   * @generated
   */
  void setChannelType(String value);

} // ModelChannel
