/**
 * generated by Xtext 2.19.0
 */
package org.openhab.core.model.rule.rules;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.openhab.core.model.rule.rules.RulesPackage
 * @generated
 */
public interface RulesFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RulesFactory eINSTANCE = org.openhab.core.model.rule.rules.impl.RulesFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Rule Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule Model</em>'.
   * @generated
   */
  RuleModel createRuleModel();

  /**
   * Returns a new object of class '<em>Variable Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable Declaration</em>'.
   * @generated
   */
  VariableDeclaration createVariableDeclaration();

  /**
   * Returns a new object of class '<em>Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule</em>'.
   * @generated
   */
  Rule createRule();

  /**
   * Returns a new object of class '<em>Event Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Trigger</em>'.
   * @generated
   */
  EventTrigger createEventTrigger();

  /**
   * Returns a new object of class '<em>Command Event Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command Event Trigger</em>'.
   * @generated
   */
  CommandEventTrigger createCommandEventTrigger();

  /**
   * Returns a new object of class '<em>Group Member Command Event Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Group Member Command Event Trigger</em>'.
   * @generated
   */
  GroupMemberCommandEventTrigger createGroupMemberCommandEventTrigger();

  /**
   * Returns a new object of class '<em>Update Event Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Update Event Trigger</em>'.
   * @generated
   */
  UpdateEventTrigger createUpdateEventTrigger();

  /**
   * Returns a new object of class '<em>Group Member Update Event Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Group Member Update Event Trigger</em>'.
   * @generated
   */
  GroupMemberUpdateEventTrigger createGroupMemberUpdateEventTrigger();

  /**
   * Returns a new object of class '<em>Changed Event Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Changed Event Trigger</em>'.
   * @generated
   */
  ChangedEventTrigger createChangedEventTrigger();

  /**
   * Returns a new object of class '<em>Group Member Changed Event Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Group Member Changed Event Trigger</em>'.
   * @generated
   */
  GroupMemberChangedEventTrigger createGroupMemberChangedEventTrigger();

  /**
   * Returns a new object of class '<em>Event Emitted Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Emitted Trigger</em>'.
   * @generated
   */
  EventEmittedTrigger createEventEmittedTrigger();

  /**
   * Returns a new object of class '<em>Timer Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Timer Trigger</em>'.
   * @generated
   */
  TimerTrigger createTimerTrigger();

  /**
   * Returns a new object of class '<em>System Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>System Trigger</em>'.
   * @generated
   */
  SystemTrigger createSystemTrigger();

  /**
   * Returns a new object of class '<em>System On Startup Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>System On Startup Trigger</em>'.
   * @generated
   */
  SystemOnStartupTrigger createSystemOnStartupTrigger();

  /**
   * Returns a new object of class '<em>System On Shutdown Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>System On Shutdown Trigger</em>'.
   * @generated
   */
  SystemOnShutdownTrigger createSystemOnShutdownTrigger();

  /**
   * Returns a new object of class '<em>Thing State Update Event Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Thing State Update Event Trigger</em>'.
   * @generated
   */
  ThingStateUpdateEventTrigger createThingStateUpdateEventTrigger();

  /**
   * Returns a new object of class '<em>Thing State Changed Event Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Thing State Changed Event Trigger</em>'.
   * @generated
   */
  ThingStateChangedEventTrigger createThingStateChangedEventTrigger();

  /**
   * Returns a new object of class '<em>Valid State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Valid State</em>'.
   * @generated
   */
  ValidState createValidState();

  /**
   * Returns a new object of class '<em>Valid State Id</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Valid State Id</em>'.
   * @generated
   */
  ValidStateId createValidStateId();

  /**
   * Returns a new object of class '<em>Valid State Number</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Valid State Number</em>'.
   * @generated
   */
  ValidStateNumber createValidStateNumber();

  /**
   * Returns a new object of class '<em>Valid State String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Valid State String</em>'.
   * @generated
   */
  ValidStateString createValidStateString();

  /**
   * Returns a new object of class '<em>Valid Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Valid Command</em>'.
   * @generated
   */
  ValidCommand createValidCommand();

  /**
   * Returns a new object of class '<em>Valid Command Id</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Valid Command Id</em>'.
   * @generated
   */
  ValidCommandId createValidCommandId();

  /**
   * Returns a new object of class '<em>Valid Command Number</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Valid Command Number</em>'.
   * @generated
   */
  ValidCommandNumber createValidCommandNumber();

  /**
   * Returns a new object of class '<em>Valid Command String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Valid Command String</em>'.
   * @generated
   */
  ValidCommandString createValidCommandString();

  /**
   * Returns a new object of class '<em>Valid Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Valid Trigger</em>'.
   * @generated
   */
  ValidTrigger createValidTrigger();

  /**
   * Returns a new object of class '<em>Valid Trigger Id</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Valid Trigger Id</em>'.
   * @generated
   */
  ValidTriggerId createValidTriggerId();

  /**
   * Returns a new object of class '<em>Valid Trigger Number</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Valid Trigger Number</em>'.
   * @generated
   */
  ValidTriggerNumber createValidTriggerNumber();

  /**
   * Returns a new object of class '<em>Valid Trigger String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Valid Trigger String</em>'.
   * @generated
   */
  ValidTriggerString createValidTriggerString();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  RulesPackage getRulesPackage();

} //RulesFactory
