/**
 * generated by Xtext 2.19.0
 */
package org.openhab.core.model.rule.rules;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Valid State String</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.openhab.core.model.rule.rules.RulesPackage#getValidStateString()
 * @model
 * @generated
 */
public interface ValidStateString extends ValidState
{
} // ValidStateString
