/**
 * generated by Xtext 2.19.0
 */
package org.openhab.core.model.rule.rules;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Valid Trigger Id</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.openhab.core.model.rule.rules.RulesPackage#getValidTriggerId()
 * @model
 * @generated
 */
public interface ValidTriggerId extends ValidTrigger
{
} // ValidTriggerId
