os: linux
dist: focal

language: java
jdk: openjdk11

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    secure: M2SYGSCzeUQWp4uvXw95tY27LaicqOENNuVQNFPaojw6pxoFYOgXwjsoMWgfkXHFa0URWippuqKZ2BzXndUtOWhG+k2+6v/VYKC9GBI9hs9DX/OQ6WaEXAtlN4zN+iOllFYK2aSGmD/XuT0u5o7BzQceqXHNXVMHwq2MD+Tb4PEfNHhtOcqLBjyQkJaXSl6R7BCuQA8W4viH/ubsWd+wOIDZHI/qhgwBQzuKXuvX7Yg2vMJWmd69HfnMKM+HL/CYkj+5JI+xumK2xQKovtUfNavQZeXWDKeHZWldxPu5w/F95GyTWDHyK9RLV/6Ztg1XV3HKWxFZNpqR/Ysj/ywMd90QJxbm1b8exCE3o2YOs+v+XQLkLk6aBuwHCHKx53kC0zmJmq1BrC0aiJ5e7FUFwYOwt+RWND5RMQo5XERqlJ9lM5i1+W48U4ujT14QCdh5yORFAtMGCU2XpLtsne2us4zQ2CAxFd19mMFB9cZKsSCtuHZhGmquZvBF9novvfHaN36/t/K0LTRti6XxoCl7zyeGaKB1NrHF3tK43zD3tFJ4+uwJhy3uNpldXnQpq0u3Ud7R5SKJApP24xe5xxfYHcWfWT7CbLeuvjXSJMxwZL6eSjHGM4FrQS35eFJVIiznla1hyK087yJ4/iRcnvsM6tDYywYJDjHbAzNUSkOH1S4=

script:
  - mvn clean verify -B -e -q -DskipChecks

before_deploy:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - git checkout master

deploy:
  skip_cleanup: true
  provider: script
  script: mvn -B -e -q deploy

branches:
  only:
    - master