/**
 * generated by Xtext 2.19.0
 */
package org.openhab.core.model.persistence.persistence;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cron Strategy</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.openhab.core.model.persistence.persistence.CronStrategy#getCronExpression <em>Cron Expression</em>}</li>
 * </ul>
 *
 * @see org.openhab.core.model.persistence.persistence.PersistencePackage#getCronStrategy()
 * @model
 * @generated
 */
public interface CronStrategy extends Strategy
{
  /**
   * Returns the value of the '<em><b>Cron Expression</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cron Expression</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cron Expression</em>' attribute.
   * @see #setCronExpression(String)
   * @see org.openhab.core.model.persistence.persistence.PersistencePackage#getCronStrategy_CronExpression()
   * @model
   * @generated
   */
  String getCronExpression();

  /**
   * Sets the value of the '{@link org.openhab.core.model.persistence.persistence.CronStrategy#getCronExpression <em>Cron Expression</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cron Expression</em>' attribute.
   * @see #getCronExpression()
   * @generated
   */
  void setCronExpression(String value);

} // CronStrategy
