/*
 * generated by Xtext 2.19.0
 */
package org.openhab.core.model.sitemap.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSitemapScopeProvider extends DelegatingScopeProvider {
}
