/**
 * generated by Xtext 2.19.0
 */
package org.openhab.core.model.rule.rules.impl;

import org.eclipse.emf.ecore.EClass;

import org.openhab.core.model.rule.rules.RulesPackage;
import org.openhab.core.model.rule.rules.ValidTriggerNumber;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Valid Trigger Number</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ValidTriggerNumberImpl extends ValidTriggerImpl implements ValidTriggerNumber
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ValidTriggerNumberImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RulesPackage.Literals.VALID_TRIGGER_NUMBER;
  }

} //ValidTriggerNumberImpl
