/*
 * generated by Xtext 2.19.0
 */
package org.openhab.core.model.thing.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractThingValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.openhab.core.model.thing.thing.ThingPackage.eINSTANCE);
		return result;
	}
}
