/**
 * generated by Xtext 2.19.0
 */
package org.openhab.core.model.sitemap.sitemap;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Frame</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.openhab.core.model.sitemap.sitemap.SitemapPackage#getFrame()
 * @model
 * @generated
 */
public interface Frame extends LinkableWidget
{
} // Frame
