/**
 * generated by Xtext 2.19.0
 */
package org.openhab.core.model.rule.rules.util;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

import org.openhab.core.model.rule.rules.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see org.openhab.core.model.rule.rules.RulesPackage
 * @generated
 */
public class RulesAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static RulesPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RulesAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = RulesPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RulesSwitch<Adapter> modelSwitch =
    new RulesSwitch<Adapter>()
    {
      @Override
      public Adapter caseRuleModel(RuleModel object)
      {
        return createRuleModelAdapter();
      }
      @Override
      public Adapter caseVariableDeclaration(VariableDeclaration object)
      {
        return createVariableDeclarationAdapter();
      }
      @Override
      public Adapter caseRule(Rule object)
      {
        return createRuleAdapter();
      }
      @Override
      public Adapter caseEventTrigger(EventTrigger object)
      {
        return createEventTriggerAdapter();
      }
      @Override
      public Adapter caseCommandEventTrigger(CommandEventTrigger object)
      {
        return createCommandEventTriggerAdapter();
      }
      @Override
      public Adapter caseGroupMemberCommandEventTrigger(GroupMemberCommandEventTrigger object)
      {
        return createGroupMemberCommandEventTriggerAdapter();
      }
      @Override
      public Adapter caseUpdateEventTrigger(UpdateEventTrigger object)
      {
        return createUpdateEventTriggerAdapter();
      }
      @Override
      public Adapter caseGroupMemberUpdateEventTrigger(GroupMemberUpdateEventTrigger object)
      {
        return createGroupMemberUpdateEventTriggerAdapter();
      }
      @Override
      public Adapter caseChangedEventTrigger(ChangedEventTrigger object)
      {
        return createChangedEventTriggerAdapter();
      }
      @Override
      public Adapter caseGroupMemberChangedEventTrigger(GroupMemberChangedEventTrigger object)
      {
        return createGroupMemberChangedEventTriggerAdapter();
      }
      @Override
      public Adapter caseEventEmittedTrigger(EventEmittedTrigger object)
      {
        return createEventEmittedTriggerAdapter();
      }
      @Override
      public Adapter caseTimerTrigger(TimerTrigger object)
      {
        return createTimerTriggerAdapter();
      }
      @Override
      public Adapter caseSystemTrigger(SystemTrigger object)
      {
        return createSystemTriggerAdapter();
      }
      @Override
      public Adapter caseSystemOnStartupTrigger(SystemOnStartupTrigger object)
      {
        return createSystemOnStartupTriggerAdapter();
      }
      @Override
      public Adapter caseSystemOnShutdownTrigger(SystemOnShutdownTrigger object)
      {
        return createSystemOnShutdownTriggerAdapter();
      }
      @Override
      public Adapter caseThingStateUpdateEventTrigger(ThingStateUpdateEventTrigger object)
      {
        return createThingStateUpdateEventTriggerAdapter();
      }
      @Override
      public Adapter caseThingStateChangedEventTrigger(ThingStateChangedEventTrigger object)
      {
        return createThingStateChangedEventTriggerAdapter();
      }
      @Override
      public Adapter caseValidState(ValidState object)
      {
        return createValidStateAdapter();
      }
      @Override
      public Adapter caseValidStateId(ValidStateId object)
      {
        return createValidStateIdAdapter();
      }
      @Override
      public Adapter caseValidStateNumber(ValidStateNumber object)
      {
        return createValidStateNumberAdapter();
      }
      @Override
      public Adapter caseValidStateString(ValidStateString object)
      {
        return createValidStateStringAdapter();
      }
      @Override
      public Adapter caseValidCommand(ValidCommand object)
      {
        return createValidCommandAdapter();
      }
      @Override
      public Adapter caseValidCommandId(ValidCommandId object)
      {
        return createValidCommandIdAdapter();
      }
      @Override
      public Adapter caseValidCommandNumber(ValidCommandNumber object)
      {
        return createValidCommandNumberAdapter();
      }
      @Override
      public Adapter caseValidCommandString(ValidCommandString object)
      {
        return createValidCommandStringAdapter();
      }
      @Override
      public Adapter caseValidTrigger(ValidTrigger object)
      {
        return createValidTriggerAdapter();
      }
      @Override
      public Adapter caseValidTriggerId(ValidTriggerId object)
      {
        return createValidTriggerIdAdapter();
      }
      @Override
      public Adapter caseValidTriggerNumber(ValidTriggerNumber object)
      {
        return createValidTriggerNumberAdapter();
      }
      @Override
      public Adapter caseValidTriggerString(ValidTriggerString object)
      {
        return createValidTriggerStringAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.RuleModel <em>Rule Model</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.RuleModel
   * @generated
   */
  public Adapter createRuleModelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.VariableDeclaration
   * @generated
   */
  public Adapter createVariableDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.Rule
   * @generated
   */
  public Adapter createRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.EventTrigger <em>Event Trigger</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.EventTrigger
   * @generated
   */
  public Adapter createEventTriggerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.CommandEventTrigger <em>Command Event Trigger</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.CommandEventTrigger
   * @generated
   */
  public Adapter createCommandEventTriggerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.GroupMemberCommandEventTrigger <em>Group Member Command Event Trigger</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.GroupMemberCommandEventTrigger
   * @generated
   */
  public Adapter createGroupMemberCommandEventTriggerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.UpdateEventTrigger <em>Update Event Trigger</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.UpdateEventTrigger
   * @generated
   */
  public Adapter createUpdateEventTriggerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.GroupMemberUpdateEventTrigger <em>Group Member Update Event Trigger</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.GroupMemberUpdateEventTrigger
   * @generated
   */
  public Adapter createGroupMemberUpdateEventTriggerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.ChangedEventTrigger <em>Changed Event Trigger</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.ChangedEventTrigger
   * @generated
   */
  public Adapter createChangedEventTriggerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.GroupMemberChangedEventTrigger <em>Group Member Changed Event Trigger</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.GroupMemberChangedEventTrigger
   * @generated
   */
  public Adapter createGroupMemberChangedEventTriggerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.EventEmittedTrigger <em>Event Emitted Trigger</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.EventEmittedTrigger
   * @generated
   */
  public Adapter createEventEmittedTriggerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.TimerTrigger <em>Timer Trigger</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.TimerTrigger
   * @generated
   */
  public Adapter createTimerTriggerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.SystemTrigger <em>System Trigger</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.SystemTrigger
   * @generated
   */
  public Adapter createSystemTriggerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.SystemOnStartupTrigger <em>System On Startup Trigger</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.SystemOnStartupTrigger
   * @generated
   */
  public Adapter createSystemOnStartupTriggerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.SystemOnShutdownTrigger <em>System On Shutdown Trigger</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.SystemOnShutdownTrigger
   * @generated
   */
  public Adapter createSystemOnShutdownTriggerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.ThingStateUpdateEventTrigger <em>Thing State Update Event Trigger</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.ThingStateUpdateEventTrigger
   * @generated
   */
  public Adapter createThingStateUpdateEventTriggerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.ThingStateChangedEventTrigger <em>Thing State Changed Event Trigger</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.ThingStateChangedEventTrigger
   * @generated
   */
  public Adapter createThingStateChangedEventTriggerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.ValidState <em>Valid State</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.ValidState
   * @generated
   */
  public Adapter createValidStateAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.ValidStateId <em>Valid State Id</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.ValidStateId
   * @generated
   */
  public Adapter createValidStateIdAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.ValidStateNumber <em>Valid State Number</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.ValidStateNumber
   * @generated
   */
  public Adapter createValidStateNumberAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.ValidStateString <em>Valid State String</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.ValidStateString
   * @generated
   */
  public Adapter createValidStateStringAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.ValidCommand <em>Valid Command</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.ValidCommand
   * @generated
   */
  public Adapter createValidCommandAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.ValidCommandId <em>Valid Command Id</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.ValidCommandId
   * @generated
   */
  public Adapter createValidCommandIdAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.ValidCommandNumber <em>Valid Command Number</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.ValidCommandNumber
   * @generated
   */
  public Adapter createValidCommandNumberAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.ValidCommandString <em>Valid Command String</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.ValidCommandString
   * @generated
   */
  public Adapter createValidCommandStringAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.ValidTrigger <em>Valid Trigger</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.ValidTrigger
   * @generated
   */
  public Adapter createValidTriggerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.ValidTriggerId <em>Valid Trigger Id</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.ValidTriggerId
   * @generated
   */
  public Adapter createValidTriggerIdAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.ValidTriggerNumber <em>Valid Trigger Number</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.ValidTriggerNumber
   * @generated
   */
  public Adapter createValidTriggerNumberAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.openhab.core.model.rule.rules.ValidTriggerString <em>Valid Trigger String</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.openhab.core.model.rule.rules.ValidTriggerString
   * @generated
   */
  public Adapter createValidTriggerStringAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //RulesAdapterFactory
